backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "scr/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiltle",name: "title",widget: "string"}
      - { label: "Decription",name: "decription",widget: "string"}
      - { label: "Author",name: "author",widget: "string"}
      - { label: "Date",name: "date",widget: "datetime"}
      - { label: "Tags",name: "tags",widget: "list", default: ["post"]}
      - { label: "Featured Image",name: "image",widget: "image"}
      - { label: "Image Caption",name: "imageAlt",widget: "string"}
      - { label: "Body",name: "body",widget: "markdown"}